
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 25
y = 25

[general]
live_config_reload = true
import = ["/Users/josh/.config/alacritty/colors.toml", "/Users/josh/.config/alacritty/fonts.toml"]
